platform :ios, "8.0"
pod "pop", "1.0.7"
pod "AFNetworking", "2.5.3"
pod "SDWebImage", "3.7.3"
pod "DACircularProgress", "2.2.0"
pod "FontAwesomeKit", "~> 2.1.0"
pod "Parse"
pod "DGActivityIndicatorView"
pod "NSDate+TimeAgo"
pod "GoogleMaps"